"""empty message

Revision ID: 1157a52c079c
Revises: d9db24ccaf7f
Create Date: 2022-09-03 22:07:35.119586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1157a52c079c'
down_revision = 'd9db24ccaf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_extension', sa.Column('address', sa.String(length=120), nullable=True))
    op.drop_column('user_extension', 'addresss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_extension', sa.Column('addresss', mysql.VARCHAR(collation='utf8_unicode_ci', length=120), nullable=True))
    op.drop_column('user_extension', 'address')
    # ### end Alembic commands ###
