"""empty message

Revision ID: 51540803371a
Revises: 6b0c07c1d054
Create Date: 2022-09-03 21:31:12.633923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51540803371a'
down_revision = '6b0c07c1d054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
